name: CI

on:
  push:
  pull_request:
  schedule:
  - cron:  '0 1 1,14,28 * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2
    - uses: FedericoCarboni/setup-ffmpeg@v1
      with:
        token: ${{ secrets.TOKEN_FFMPEG }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: windows temp set.
      run: |
        set TMP=%USERPROFILE%\AppData\Local\Temp
        set TEMP=%USERPROFILE%\AppData\Local\Temp
    - name: Run test script
      run: python ./scripts/ci_test.py

